### ISSUE TITLE
[DataCap Application] <Wuhan Nalai> - <Nalai Film>

### ISSUE THREAD

**Issue by bonpreu** [ipfsforcezuofu/ipfsforce-allocator#8]
### Data Owner Name

Wuhan Nalai Film and Television Culture Media Co., Ltd.

### Data Owner Country/Region

China

### Data Owner Industry

Arts & Recreation

### Website

http://www.whnlys.com/

### Social Media Handle

http://www.whnlys.com/

### Social Media Type

WeChat

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

2PiB

### Expected size of single dataset (one copy)

500TiB

### Number of replicas to store

4

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f3sb5dxwwoeawhj4cxdhb5ir5qadc3p7cocxw4i7gem2iuj6isvthkz6dqj2btdxxa7behz22l2ve3bd76viva

### Data Type of Application

Private Commercial/Enterprise

### Custom multisig

- [X] Use Custom Multisig

### Identifier

 Use Custom Multisig

### Share a brief history of your project and organization

```text
Wuhan Nalai is a new media film and television production company. It's main business includes production and joint production, publicity and distribution, radio and television program production, performance brokerage, etc. It is committed to disseminating excellent traditional culture and creating high-quality new media film and television.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### If answered yes, what are the other projects/ecosystem stakeholders

```text
No response
```

### Describe the data being stored onto Filecoin

```text
Trailers, samples, photos, recordings of the films produced by our company.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you answered "Other" in the previous question, enter the details here

```text
Copyrighted movie data, currently stored in IDC.
```

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Graphsplit,I prefer offline transmission
```

### If you are not preparing the data, who will prepare the data?  (Provide name and business)

```text
No response
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
Yes; we have a larger amount of data and want to be able to back it up more securely.
This is an applied EFIL+ project, 
historical link: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1253
https://github.com/ipfsforcezuofu/ipfsforce-allocator/issues/2
```

### Please share a sample of the data

```text
http://www.whnlys.com/vod_show.asp?id=179
http://www.whnlys.com/vod_show.asp?id=177
http://www.whnlys.com/vod_show.asp?id=93
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### If you chose not to confirm, what was the reason

```text
This is private data for archival and internal employee use only. For E-Fil+ project.
```

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers

Others

### How did you find your storage providers

Slack, Partners

### If you answered "Others" in the previous question, what is the tool or platform you used

```text
No response
```

### Please list the provider IDs and location of the storage providers you will be working with.

```text
1,f01228000  Seoul, Seoul, KR
2,f0522948   Singapore
3,f01100139   JP
4,f03137648   New York, USA
```

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
No response
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by ipfsforcezuofu** [comment]
I noticed that f03137648 is a new SP. Could you please send me an email with the SP's information for KYC?

**Comment by ipfsforcezuofu** [comment]
I have kindly received your email, and the KYC process is now completed. Here is the schedule:
First: 125t
Second: 250t
Third: 500t
Fourth: 1125t

**Comment by ipfsforcezuofu** [comment]
@bonpreu The DC application cannot be refiled due to the attached issue. I suggest reopening issue 2 to address your request. Does this work for you?
[Client Address Issue.pdf](https://github.com/user-attachments/files/16842871/Client.Address.Issue.pdf)

**Comment by bonpreu** [comment]
@ipfsforcezuofu  agree

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger
